spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath:db/master.xml
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
    enabled: true
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:~/CAR_DB
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

springdoc:
  pathsToMatch: /api/cars

application:
  abtest:
    ponderation-strategy: true