spring:
  profiles:
    active: mysql
  liquibase:
    change-log: classpath:db/master.xml
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
    enabled: true
  h2:
    console:
      enabled: false
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost/frontapp?serverTimezone=Africa/Douala&useUnicode=true&characterEncoding=utf8
    username: frontapp
    password: frontapp2020
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

